'use strict';
const $=id=>document.getElementById(id), STORAGE='brisa-spanish2010-v1';
let state={step:0,seen:[],started:false,missing:false,picked:false,finished:false,hint:0,messages:[]};
let saving=false;
try{const raw=localStorage.getItem(STORAGE);if(raw){const saved=JSON.parse(raw);if(saved.version===1&&Number.isInteger(saved.state.step)&&saved.state.step>=0&&saved.state.step<=7&&Array.isArray(saved.state.messages)&&Array.isArray(saved.state.seen)){state=saved.state;saving=true;}}}catch(e){}
$('save').checked=saving;
function save(){if(!saving)return;try{localStorage.setItem(STORAGE,JSON.stringify({version:1,state}));$('saveStatus').textContent='Guardado solo en este navegador.';}catch(e){$('saveStatus').textContent='No se pudo guardar. Puedes seguir jugando.';}}
function add(who,text){state.messages.push({who,text});renderLog();save();}
function renderLog(){$('log').replaceChildren();for(const m of state.messages){const el=document.createElement('div');el.className='message '+(m.who==='Tú'?'you':m.who==='Guía'?'guide':'npc');const name=document.createElement('span');name.className='speaker';name.textContent=m.who;const p=document.createElement('p');p.textContent=m.text;el.append(name,p);$('log').append(el);}$('log').scrollTop=$('log').scrollHeight;}
function canTalk(){return state.started&&!(state.step===2&&!state.missing)&&!(state.step===6&&!state.picked)&&!state.finished;}
function update(){const goals=[['Explorar la reserva y el pasaporte',state.seen.includes('reservation')&&state.seen.includes('passport')],['Registrarte con Lucía',state.step>=2],['Explicar y describir la maleta',state.step>=5],['Recuperar la maleta y la llave',state.step>=7],['Escribir una reflexión',state.finished]];const done=goals.filter(g=>g[1]).length;$('count').textContent=done+' / 5';$('progress').value=done;$('goals').replaceChildren();goals.forEach(([title,ok])=>{const li=document.createElement('li');li.className=ok?'done':'';li.textContent=(ok?'✓ ':'○ ')+title;$('goals').append(li);});$('items').replaceChildren();[['reservation','▤ Reserva'],['passport','▣ Pasaporte'],['belongings','◈ Pertenencias'],...(state.picked?[['suitcase','🧳 Maleta']]:[]),...(state.step>=7?[['key','⚿ Llave 204']]:[])].forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.className=state.seen.includes(id)||id==='key'||id==='suitcase'?'found':'';b.onclick=()=>inspect(id);$('items').append(b);});$('pickup').hidden=!(state.step===6&&!state.picked);$('answerForm').hidden=!canTalk();$('hint').hidden=state.step===7;$('interaction').hidden=state.finished;$('ending').hidden=!state.finished;$('task').textContent=!state.started?'Primero: explora tu reserva y tu pasaporte.':state.step===2&&!state.missing?'Explora tus pertenencias junto al sillón.':state.step===6&&!state.picked?'El taxi llegó. Recoge la maleta en la escena.':state.step===7?'Antes de irte: escribe 2–3 frases sobre lo que pasó.':LESSON[state.step]?.title||'';$('answerLabel').textContent=state.step===7?'Tu reflexión (sin evaluación automática)':'Tu respuesta en español';if(state.step===7)$('answer').placeholder='Llegué… Dejé… Lucía me ayudó…';renderHints();save();}
function inspect(id){if(!state.seen.includes(id))state.seen.push(id);const content={reservation:'<p class="eyebrow">DOCUMENTO 01</p><h2>Tu reserva</h2><div class="card"><strong>Alex Rivera</strong><br>Hotel Brisa · México<br>Dos noches · una persona<br>Habitación 204</div><p>Eres Alex. Llegaste hoy de viaje. Habla con Lucía para registrarte.</p>',passport:'<p class="eyebrow">DOCUMENTO 02 · FICTICIO</p><h2>Tu pasaporte</h2><div class="card">Nombre: <strong>Alex Rivera</strong><br>Documento de práctica · sin datos reales</div><p>Para entregarlo: «Aquí tiene mi pasaporte». Para practicar pronombres: «Se lo doy» (a usted + el pasaporte).</p>',belongings:'<p class="eyebrow">JUNTO AL SILLÓN</p><h2>Un momento…</h2><p>Tienes tu mochila y el recibo del taxi, pero falta tu maleta.</p><div class="card"><strong>Recibo: Taxi Sol · taxi 24</strong><br>Aeropuerto → Hotel Brisa<br>Recuerdas: pusiste la maleta en el taxi. Saliste del taxi sin ella.</div><div class="bag-picture" role="img" aria-label="Foto de una maleta azul con cinta amarilla"></div><p>Foto de tu maleta: azul, con una cinta amarilla. Puedes consultar esta foto cuando quieras.</p>',suitcase:'<h2>¡Aquí está!</h2><div class="bag-picture" role="img" aria-label="Maleta azul con cinta amarilla"></div><p>El conductor la trajo. ¡Ya tienes tu maleta!</p>',key:'<h2>Habitación 204</h2><p>Lucía te dio la llave. Tu habitación está lista.</p>'};$('inspectBody').innerHTML=content[id];$('inspect').showModal();if(id==='belongings'&&state.step===2&&!state.missing){state.missing=true;add('Guía','¡Falta tu maleta! Recuerdas que la dejaste en el taxi.');add('Lucía',LESSON[2].question);}update();}
document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>inspect(b.dataset.inspect));$('close').onclick=()=>$('inspect').close();
$('reception').onclick=()=>{if(!state.seen.includes('reservation')||!state.seen.includes('passport')){add('Guía','Mira tu reserva y abre el pasaporte en tu inventario antes de hablar con Lucía.');return;}if(!state.started){state.started=true;add('Lucía',LESSON[0].question);}else if(state.step===2&&!state.missing){add('Lucía','Revise sus pertenencias junto al sillón.');}else if(state.step===6&&!state.picked){add('Lucía','¡Su maleta está en la entrada! Puede recogerla.');}else if(canTalk()&&state.step<7){add('Lucía',LESSON[state.step].question);}update();if(canTalk())$('answer').focus();};
$('pickup').onclick=()=>{if(state.step!==6||state.picked)return;state.picked=true;add('Guía','El conductor te entrega la maleta azul. «¡Gracias por traerla!»');add('Lucía',LESSON[6].question);update();$('answer').focus();};
function renderHints(){$('hints').replaceChildren();if(!canTalk()||state.step===7||!state.hint)return;const s=LESSON[state.step];const p=document.createElement('p');p.textContent=state.hint===1?'Vocabulario: '+s.vocab:state.hint===2?'Empieza así: '+s.starter:'Puedes probar una respuesta. Algunas opciones son bromas: Lucía te ayudará a reformularlas.';$('hints').append(p);if(state.hint>=3){const choices=[s.answers[0],...s.distractors.map(d=>d[0]),s.answers[1]];choices.forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>submit(t);$('hints').append(b);});}}
$('hint').onclick=()=>{state.hint=Math.min(3,state.hint+1);update();};
function submit(text){text=text.trim();if(!text||!canTalk())return;add('Tú',text);$('answer').value='';if(state.step===7){if(text.length<20){add('Guía','Añade un poco más: ¿cómo llegaste?, ¿dónde dejaste la maleta?, ¿quién te ayudó? Puedes usar: «Vine en taxi. Dejé mi maleta allí. Lucía me ayudó».');return;}state.finished=true;add('Guía','¡Gracias por tu reflexión! No la calificamos automáticamente. Revisa tus verbos en pretérito; puedes comparar con: «Vine en taxi. Dejé mi maleta allí. Lucía me ayudó y me dio la llave».');update();return;}const s=LESSON[state.step],result=matchAnswer(s,text);if(result.kind==='distractor'){add('Lucía',result.reply);state.hint=Math.max(2,state.hint);update();return;}if(result.kind==='unknown'){add('Guía','Tu frase puede ser válida; este diálogo reconoce un grupo limitado de respuestas. Prueba una frase más breve o usa una pista. No pierdes puntos.');state.hint=Math.min(3,state.hint+1);update();return;}if(result.kind==='repair'||result.kind==='typo')add('Guía','¡Se entiende! Un modelo para practicar: «'+result.model+'»');if(s.id==='where'&&!/dej|olvid/i.test(text))add('Guía','Para contar lo que pasó, puedes decir: «La dejé en el taxi».');if(s.id==='passport')add('Guía','«Se lo doy»: se = a usted; lo = el pasaporte.');if(s.id==='key')add('Guía','«¿Me la da?»: me = a mí; la = la llave.');add('Lucía',s.reply);state.step++;state.hint=0;if(state.step===7)add('Guía','Ya tienes todo. Escribe 2–3 frases en pretérito sobre tu aventura. Verbos útiles: vine, dejé, encontré, me ayudó, me dio.');update();}
$('answerForm').onsubmit=e=>{e.preventDefault();submit($('answer').value);};$('answer').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('answerForm').requestSubmit();}};
function transcript(){return '¿Dónde está mi maleta? · Español 2010\nPráctica guiada · sin calificación automática\n\n'+state.messages.map(m=>m.who+': '+m.text).join('\n\n');}
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(transcript());$('copyStatus').textContent='Conversación copiada.';}catch(e){$('copyStatus').textContent='El navegador no permite copiar aquí. Usa «Descargar texto».';}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([transcript()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mi-aventura.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('save').onchange=()=>{saving=$('save').checked;if(saving)save();else{try{localStorage.removeItem(STORAGE);}catch(e){}$('saveStatus').textContent='Guardado desactivado.';}};
$('restart').onclick=()=>{if(!confirm('¿Reiniciar la aventura? Se borrará esta conversación y el progreso guardado.'))return;try{localStorage.removeItem(STORAGE);}catch(e){}state={step:0,seen:[],started:false,missing:false,picked:false,finished:false,hint:0,messages:[]};$('answer').value='';$('answer').placeholder='Escribe aquí…';$('copyStatus').textContent='';add('Guía','Acabas de llegar al hotel Brisa. Explora tu reserva y tu pasaporte; después, habla con Lucía.');update();};
if(!state.messages.length)add('Guía','Acabas de llegar al hotel Brisa. Explora tu reserva y tu pasaporte; después, habla con Lucía.');renderLog();update();
