/* Professor editing guide: add complete sentences to answers; acceptable imperfect
   language to repairs [student phrase, Spanish model]. Keep distractors contextual. */
const LESSON = [
 {id:'checkin', title:'Registrarte', question:'¡Bienvenido al hotel Brisa! Soy Lucía. ¿Tiene una reserva?', answers:['Sí, tengo una reserva a nombre de Alex Rivera.','Tengo una reserva.','Quisiera registrarme.','Sí, a nombre de Alex Rivera.'], vocab:'reserva · a nombre de · registrarme', starter:'Sí, tengo…', reply:'Sí, Alex Rivera: dos noches. ¿Me da su pasaporte?', repairs:[['Yo tener una reserva','Tengo una reserva.']], distractors:[['Tengo una reservación para mi dragón.','¡Espero que no caliente la piscina! Para su habitación: «Tengo una reserva». ¿Tiene una reserva?']]},
 {id:'passport', title:'Presentar el pasaporte', question:'¿Me da su pasaporte, por favor?', answers:['Sí, aquí tiene mi pasaporte.','Sí, se lo doy.','Aquí está.','Aquí tiene.','Se lo doy.'], vocab:'dar · se lo · aquí tiene',starter:'Sí, se lo…',reply:'Gracias. Ya tengo sus datos. Revise sus pertenencias junto al sillón.',repairs:[['Sí, le lo doy','Sí, se lo doy.']],distractors:[['Le doy una pizza.','¡Qué amable! La pizza puede esperar. «Aquí tiene mi pasaporte». ¿Me da su pasaporte?']]},
 {id:'where', title:'Explicar lo que pasó', question:'No veo su maleta. ¿Dónde la dejó?',answers:['Dejé mi maleta en el taxi.','La dejé en el taxi.','Olvidé mi maleta en el taxi.','Mi maleta está en el taxi.','Está en el taxi.'],vocab:'dejar → dejé · olvidar → olvidé · el taxi',starter:'La dejé…',reply:'Entiendo. Vamos a buscarla. ¿Cómo llegó del aeropuerto al hotel?',repairs:[['Yo dejó mi maleta en el taxi','Dejé mi maleta en el taxi.'],['Dejé mi suitcase en el taxi','Dejé mi maleta en el taxi.']],distractors:[['Dejé mi maleta en la luna','¡Un viaje muy largo! «La dejé en el taxi». ¿Dónde dejó su maleta aquí en la Tierra?'],['Mi suitcase se fue de vacaciones sin mí','¡Su maleta empezó las vacaciones primero! Para buscarla: «La dejé en el taxi». ¿Dónde la vio por última vez?']]},
 {id:'travel',title:'Recordar el viaje',question:'¿Cómo llegó del aeropuerto al hotel?',answers:['Tomé un taxi en la salida del aeropuerto.','Vine en taxi.','Tomé un taxi.','Fui al hotel en taxi.','Llegué en taxi.'],vocab:'venir → vine · tomar → tomé · la salida',starter:'Vine…',reply:'Muy bien. El recibo dice Taxi Sol, número 24. ¿Cómo es su maleta?',repairs:[['Venió en taxi','Vine en taxi.'],['Yo vine en un taxi','Vine en un taxi.'],['Yo tomar un taxi','Tomé un taxi.']],distractors:[['Busqué el éxito del aeropuerto','¡Ojalá su viaje tenga mucho éxito! «Salida» significa exit; «éxito» significa success. «Tomé un taxi en la salida». ¿Cómo llegó al hotel?']]},
 {id:'describe',title:'Describir la maleta',question:'¿Cómo es su maleta? Mire la foto en sus pertenencias.',answers:['Es azul y tiene una cinta amarilla.','Mi maleta es azul.','Es azul.','Tiene una cinta amarilla.','Es una maleta azul con una cinta amarilla.'],vocab:'azul · cinta amarilla · tiene',starter:'Es azul y…',reply:'Perfecto. Una maleta azul con cinta amarilla. Tengo el número del conductor. ¿Quiere que lo llame?',repairs:[['Es blue con una cinta amarilla','Es azul con una cinta amarilla.'],['La maleta es azula','La maleta es azul.']],distractors:[['Es invisible y canta ópera.','¡Así sería fácil oírla! En su foto es azul: «Es azul y tiene una cinta amarilla». ¿Cómo es su maleta?']]},
 {id:'help',title:'Pedir ayuda',question:'Tengo el número del conductor. ¿Quiere que lo llame?',answers:['Sí, llámelo, por favor.','Sí, por favor.','¿Puede llamarlo, por favor?','¿Me puede ayudar?','Sí, ¿puede llamar al conductor?'],vocab:'llamarlo · ayudarme · por favor',starter:'¿Puede…',reply:'El conductor la encontró. ¡Está en la entrada! Haga clic en la maleta para recogerla.',repairs:[['Sí, llama él por favor','Sí, llámelo, por favor.']],distractors:[['Llame a todos los pingüinos.','¡Nuestro equipo de pingüinos está de vacaciones! «Sí, llámelo, por favor». ¿Llamo al conductor?']]},
 {id:'key',title:'Recibir la llave',question:'¡Ya tiene su maleta! ¿Qué más necesita para entrar en su habitación?',answers:['¿Me da la llave, por favor?','Necesito la llave.','¿Me la da, por favor?','La llave, por favor.','¿Puede darme la llave?'],vocab:'la llave · darme · me la',starter:'¿Me da…',reply:'Aquí tiene la llave de la habitación 204. ¡Que disfrute su estancia!',repairs:[['Necesito el llave','Necesito la llave.']],distractors:[['Necesito un castillo inflable.','¡La habitación 204 es más cómoda! «Necesito la llave». ¿Qué necesita para entrar?']]}
];
if(typeof module!=='undefined') module.exports=LESSON;
